services:
  server:
    container_name: kmcserver
    restart: always
    image: ghcr.io/ripplebytes/kmc_pelican:latest
    build:
      context: .
    ports:
      - "4322:8000"
    volumes:
      - ./media_temp/:/app/media/
      - ./db_temp/:/app/db/