# Generated by Django 5.1.1 on 2024-09-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadwayInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carriage_width', models.FloatField()),
                ('divided_undivided', models.CharField(max_length=10)),
                ('intersection', models.CharField(max_length=3)),
                ('intersection_type', models.CharField(blank=True, max_length=50, null=True)),
                ('num_lanes', models.IntegerField(blank=True, null=True)),
                ('footpath', models.CharField(max_length=15)),
                ('width_each_side', models.FloatField(blank=True, null=True)),
                ('one_way_two_way', models.CharField(max_length=10)),
                ('traffic_lights', models.CharField(max_length=3)),
                ('traffic_lights_working', models.CharField(blank=True, max_length=15, null=True)),
                ('num_traffic_lights', models.IntegerField(blank=True, null=True)),
                ('zebra_crossings', models.CharField(max_length=3)),
                ('num_zebra_crossings', models.IntegerField(blank=True, null=True)),
                ('zebra_width', models.FloatField(blank=True, null=True)),
                ('foot_over_bridge', models.CharField(max_length=3)),
                ('num_foot_over_bridges', models.IntegerField(blank=True, null=True)),
                ('power_source', models.CharField(blank=True, max_length=50, null=True)),
                ('viable_installation', models.CharField(max_length=3)),
                ('reason', models.TextField(blank=True, null=True)),
                ('pictures_near_side', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('traffic_lights_pictures', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('foot_over_bridge_picture', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('power_source_picture', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('electric_poles_picture', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
