# Generated by Django 5.1.1 on 2024-09-18 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('school_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=10)),
                ('ward', models.PositiveIntegerField()),
                ('entrance_image', models.ImageField(upload_to='entrances/')),
                ('multiple_entrances', models.BooleanField(default=False)),
                ('school_coordinates', models.CharField(max_length=100)),
                ('bus_facility', models.BooleanField(default=False)),
                ('bus_count', models.PositiveIntegerField(blank=True, null=True)),
                ('bus_ownership', models.CharField(blank=True, choices=[('owned', 'School Owned'), ('hired', 'Hired'), ('mixed', 'Mixed')], max_length=10, null=True)),
                ('owned_buses_count', models.PositiveIntegerField(blank=True, null=True)),
                ('hired_buses_count', models.PositiveIntegerField(blank=True, null=True)),
                ('bus_parking', models.CharField(blank=True, choices=[('inside', 'Inside Compound'), ('outside', 'Outside Compound')], max_length=10, null=True)),
                ('pick_drop_location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_image', models.ImageField(upload_to='entrances/')),
                ('entrance_location', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrances', to='api.school')),
            ],
        ),
    ]
