# Generated by Django 5.1.1 on 2024-09-28 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_school_entrance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='school_coordinates',
            new_name='school_coordinates_latitude',
        ),
        migrations.RemoveField(
            model_name='school',
            name='entrance_image',
        ),
        migrations.AddField(
            model_name='school',
            name='closing_time_summer',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='closing_time_winter',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='opening_time_summer',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='opening_time_winter',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='same_timings_all_year',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_coordinates_longitude',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='ward',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32)]),
        ),
        migrations.CreateModel(
            name='EntranceExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='entrances/')),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('is_entrance', models.BooleanField(default=False)),
                ('is_exit', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrances', to='api.school')),
            ],
        ),
        migrations.CreateModel(
            name='FinalizationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carriage_way_width', models.FloatField()),
                ('footpath_info', models.TextField(blank=True, null=True)),
                ('zebra_crossing_info', models.TextField(blank=True, null=True)),
                ('electrical_infrastructure', models.TextField(blank=True, null=True)),
                ('traffic_direction', models.CharField(max_length=20)),
                ('installation_point_latitude', models.CharField(max_length=100)),
                ('installation_point_longitude', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.school')),
            ],
        ),
        migrations.CreateModel(
            name='RoadwayFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carriage_width', models.FloatField()),
                ('carriage_direction', models.CharField(choices=[('North-South', 'North-South'), ('East-West', 'East-West'), ('North', 'North'), ('South', 'South'), ('East', 'East'), ('West', 'West')], max_length=20)),
                ('divided', models.CharField(choices=[('Undivided', 'Undivided'), ('Central Refuge', 'Central Refuge'), ('Barrier', 'Barrier')], max_length=20)),
                ('is_at_intersection', models.BooleanField(default=False)),
                ('intersection_type', models.CharField(blank=True, choices=[('T-Junction', 'T-Junction'), ('4-Legged-Intersection', '4-Legged-Intersection'), ('Y-Junction', 'Y-Junction'), ('Staggered-T-Junction', 'Staggered-T-Junction'), ('Rotary-Or-Roundabout', 'Rotary-Or-Roundabout')], max_length=50, null=True)),
                ('number_of_lanes', models.IntegerField(blank=True, null=True)),
                ('central_marking', models.CharField(blank=True, choices=[('None', 'None'), ('Broken-Single', 'Broken-Single'), ('Broken-Double', 'Broken-Double'), ('Continuous-Single', 'Continuous-Single'), ('Continuous-Double', 'Continuous-Double')], max_length=50, null=True)),
                ('footpath_info', models.TextField(blank=True, null=True)),
                ('nearby_facilities', models.TextField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.school')),
            ],
        ),
        migrations.DeleteModel(
            name='Entrance',
        ),
    ]
