# Generated by Django 5.1.1 on 2024-09-28 16:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_roadwayfacilityfar_roadwayfacilitynear_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roadwayfacilitynear',
            old_name='width_each_side',
            new_name='width_side_one',
        ),
        migrations.RemoveField(
            model_name='roadwayfacilityfar',
            name='both_sides_or_one_side',
        ),
        migrations.RemoveField(
            model_name='roadwayfacilitynear',
            name='both_sides_or_one_side',
        ),
        migrations.RemoveField(
            model_name='roadwayfacilitynear',
            name='footpath_info',
        ),
        migrations.RemoveField(
            model_name='roadwayfacilitynear',
            name='one_way_two_way',
        ),
        migrations.AddField(
            model_name='roadwayfacilityfar',
            name='street_side_one',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='roadwayfacilityfar',
            name='street_side_two',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='roadwayfacilitynear',
            name='footpath',
            field=models.CharField(choices=[('One-Side', 'One-Side'), ('Both-Side', 'Both-Side'), ('None', 'None')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadwayfacilitynear',
            name='street_side_one',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='roadwayfacilitynear',
            name='street_side_two',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='roadwayfacilitynear',
            name='width_side_two',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roadwayfacilityfar',
            name='electric_poles_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='roadwayfacilityfar',
            name='foot_over_bridge_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='roadwayfacilityfar',
            name='on_street_vehicle_parking',
            field=models.CharField(choices=[('None', 'None'), ('Both-Side', 'Both-Side'), ('One-Side', 'One-Side')], max_length=10),
        ),
        migrations.AlterField(
            model_name='roadwayfacilityfar',
            name='pictures_far_side',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='roadwayfacilityfar',
            name='pictures_near_side',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='roadwayfacilityfar',
            name='power_source_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='roadwayfacilityfar',
            name='traffic_lights_pictures',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='roadwayfacilitynear',
            name='divided',
            field=models.CharField(choices=[('Undivided', 'Undivided'), ('Central-Refuge', 'Central-Refuge'), ('Barrier', 'Barrier')], max_length=20),
        ),
        migrations.AlterField(
            model_name='roadwayfacilitynear',
            name='electric_poles_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='roadwayfacilitynear',
            name='foot_over_bridge_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='roadwayfacilitynear',
            name='on_street_vehicle_parking',
            field=models.CharField(choices=[('None', 'None'), ('Both-Side', 'Both-Side'), ('One-Side', 'One-Side')], max_length=10),
        ),
        migrations.AlterField(
            model_name='roadwayfacilitynear',
            name='pictures_far_side',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='roadwayfacilitynear',
            name='pictures_near_side',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='roadwayfacilitynear',
            name='power_source_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='roadwayfacilitynear',
            name='traffic_lights_pictures',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='roadwayfacilitynear',
            name='traffic_lights_working',
            field=models.CharField(blank=True, choices=[('Working', 'Working'), ('Not-Working', 'Not-Working')], max_length=15, null=True),
        ),
    ]
