# Generated by Django 5.1.1 on 2024-09-28 17:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_width_each_side_roadwayfacilitynear_width_side_one_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roadwayfacilityfar',
            old_name='width_each_side',
            new_name='width_side_one',
        ),
        migrations.RemoveField(
            model_name='roadwayfacilityfar',
            name='footpath_info',
        ),
        migrations.RemoveField(
            model_name='roadwayfacilityfar',
            name='one_way_two_way',
        ),
        migrations.AddField(
            model_name='roadwayfacilityfar',
            name='footpath',
            field=models.CharField(choices=[('One-Side', 'One-Side'), ('Both-Side', 'Both-Side'), ('None', 'None')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadwayfacilityfar',
            name='width_side_two',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roadwayfacilityfar',
            name='divided',
            field=models.CharField(choices=[('Undivided', 'Undivided'), ('Central-Refuge', 'Central-Refuge'), ('Barrier', 'Barrier')], max_length=20),
        ),
        migrations.AlterField(
            model_name='roadwayfacilityfar',
            name='traffic_lights_working',
            field=models.CharField(blank=True, choices=[('Working', 'Working'), ('Not-Working', 'Not-Working')], max_length=15, null=True),
        ),
    ]
