# Generated by Django 5.1.1 on 2024-09-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_width_each_side_roadwayfacilityfar_width_side_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='bus_parking',
            field=models.CharField(blank=True, choices=[('Inside-Compound', 'Inside-Compound'), ('Outside-Compound', 'Outside-Compound')], max_length=100, null=True),
        ),
    ]
