# Generated by Django 5.1.1 on 2024-09-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_school_bus_parking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='pick_drop_location',
            new_name='bus_parking_latitude',
        ),
        migrations.AddField(
            model_name='school',
            name='bus_parking_longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='drop_off_location_latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='drop_off_location_longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='pick_up_location_latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='pick_up_location_longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
