# Generated by Django 5.1.1 on 2024-09-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_pick_drop_location_school_bus_parking_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='bus_ownership',
            field=models.CharField(blank=True, choices=[('School-Owned', 'School-Owned'), ('Hired', 'Hired'), ('Mixed', 'Mixed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=10),
        ),
    ]
