# Generated by Django 5.1.1 on 2024-10-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_foot_over_bridge_picture_roadwayfacilityfar_foot_over_bridge_pic_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadwayfacilitynear',
            name='electric_poles_latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roadwayfacilitynear',
            name='electric_poles_longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roadwayfacilitynear',
            name='street_side_one_latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roadwayfacilitynear',
            name='street_side_one_longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roadwayfacilitynear',
            name='street_side_two_latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roadwayfacilitynear',
            name='street_side_two_longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
