# Generated by Django 5.1.1 on 2024-10-01 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_roadwayfacilityfar_electric_poles_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadwayfacilityfar',
            name='footpath',
            field=models.CharField(choices=[('None', 'None'), ('Both-Side', 'Both-Side'), ('One-Side', 'One-Side')], max_length=100),
        ),
    ]
