# Generated by Django 5.1.1 on 2024-10-01 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_roadwayfacilityfar_footpath'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalizationform',
            old_name='electrical_infrastructure',
            new_name='viable_power_source',
        ),
        migrations.RemoveField(
            model_name='finalizationform',
            name='carriage_way_width',
        ),
        migrations.RemoveField(
            model_name='finalizationform',
            name='footpath_info',
        ),
        migrations.RemoveField(
            model_name='finalizationform',
            name='installation_point_latitude',
        ),
        migrations.RemoveField(
            model_name='finalizationform',
            name='installation_point_longitude',
        ),
        migrations.RemoveField(
            model_name='finalizationform',
            name='traffic_direction',
        ),
        migrations.RemoveField(
            model_name='finalizationform',
            name='zebra_crossing_info',
        ),
        migrations.AddField(
            model_name='finalizationform',
            name='data_far',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.roadwayfacilityfar'),
        ),
        migrations.AddField(
            model_name='finalizationform',
            name='data_near',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.roadwayfacilitynear'),
        ),
        migrations.AddField(
            model_name='finalizationform',
            name='far_side_latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='finalizationform',
            name='far_side_longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='finalizationform',
            name='far_side_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='finalizationform',
            name='is_near_side',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='finalizationform',
            name='is_zebra_crossings_available',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='finalizationform',
            name='near_side_latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='finalizationform',
            name='near_side_longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='finalizationform',
            name='near_side_picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
