# Generated by Django 5.1.1 on 2024-10-01 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_electrical_infrastructure_finalizationform_viable_power_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalizationform',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.school'),
        ),
    ]
