# Generated by Django 5.1.1 on 2024-10-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_school_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadwayfacilityfar',
            name='is_partial_one_way',
        ),
        migrations.RemoveField(
            model_name='roadwayfacilityfar',
            name='is_partial_two_way',
        ),
        migrations.RemoveField(
            model_name='roadwayfacilitynear',
            name='is_partial_one_way',
        ),
        migrations.RemoveField(
            model_name='roadwayfacilitynear',
            name='is_partial_two_way',
        ),
        migrations.AddField(
            model_name='roadwayfacilityfar',
            name='traffic_lights_pic_four',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='roadwayfacilitynear',
            name='traffic_lights_pic_four',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='roadwayfacilityfar',
            name='carriage_way_direction',
            field=models.CharField(choices=[('One-Way', 'One-Way'), ('Two-Way', 'Two-Way'), ('Partial-One-Way', 'Partial-One-Way'), ('Partial-Two-Way', 'Partial-Two-Way')], max_length=50),
        ),
        migrations.AlterField(
            model_name='roadwayfacilitynear',
            name='carriage_way_direction',
            field=models.CharField(choices=[('One-Way', 'One-Way'), ('Two-Way', 'Two-Way'), ('Partial-One-Way', 'Partial-One-Way'), ('Partial-Two-Way', 'Partial-Two-Way')], max_length=50),
        ),
    ]
