# Generated by Django 5.1.1 on 2024-10-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_roadwayfacilityfar_is_partial_one_way_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roadwayfacilitynear',
            old_name='partial_end_time',
            new_name='partial_end_time_one_way',
        ),
        migrations.RenameField(
            model_name='roadwayfacilitynear',
            old_name='partial_start_time',
            new_name='partial_end_time_two_way',
        ),
        migrations.AddField(
            model_name='roadwayfacilitynear',
            name='partial_direction_one_way',
            field=models.CharField(blank=True, choices=[('North-South', 'North-South'), ('East-West', 'East-West'), ('North', 'North'), ('South', 'South'), ('East', 'East'), ('West', 'West')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='roadwayfacilitynear',
            name='partial_direction_two_way',
            field=models.CharField(blank=True, choices=[('North-South', 'North-South'), ('East-West', 'East-West'), ('North', 'North'), ('South', 'South'), ('East', 'East'), ('West', 'West')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='roadwayfacilitynear',
            name='partial_start_time_one_way',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roadwayfacilitynear',
            name='partial_start_time_two_way',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roadwayfacilitynear',
            name='carriage_way_direction',
            field=models.CharField(choices=[('One-Way', 'One-Way'), ('Two-Way', 'Two-Way'), ('Partial', 'Partial')], max_length=50),
        ),
    ]
